### ISSUE TITLE
App market does not work

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#117]
Hi.

We developed an app market prototype when we created the ANT manager.
However, it can be used for testing, but there is a problem in general use.
Some improvements are needed in relation to the app market for the expansion of the ANT ecosystem.
- Need to prepare a process for ANT app developers.
- Need a server to store and manage the ANT app package.

**Comment by RedCarrottt** [comment]
I will try to resolve it after I complete to handle Issue #122.

**Comment by RedCarrottt** [comment]
Due to Issue #137, we have a long-term plan of ANT; changing multi-app architecture to single-app architecture.
It is because most of IoT devices have single-app scenario and multi-app architecture means just complicated and useless one.
Therefore, app market is also not required for now.
I close this issue.
