### ISSUE TITLE
SDP session registration error

### ISSUE THREAD

**Issue by sinban04** [SKKU-ESLAB/ANT#44]
I tested ANT framework on Raspberry Pi3 - Stretch (dist).
After install ANT into system successfully, it could make error related to SDP session registration.

I'm not sure what causes this error, but after i reboot, it works well.
As soon as i figured it out, i will debug the error.
Until then, please reboot when you meet the error below.

![image](https://user-images.githubusercontent.com/15901475/32278744-005ccaee-bf5a-11e7-8347-9fc3d0068af9.png)

**Comment by sinban04** [comment]
It works well now, 

![image](https://user-images.githubusercontent.com/15901475/32278794-2bad8c24-bf5a-11e7-9a8c-0be9fb7dcbbf.png)
****

**Comment by RedCarrottt** [comment]
It seems that it is because of SDP protocol to communicate with ```bluez``` 4.x.

As I know, recent version of `bluez` introduced more common IPC manner like **d-bus**, instead of SDP.

Therefore, I think **converting SDP-related code into d-bus** would be good.

If we do that job, as an additional benefit, we can remove `dep/bluez-4.101` and use recent bluez package.

**Comment by RedCarrottt** [comment]
This problem is resolved, and bluez version issue is duplicated with Issue #107.

So I close this issue.
